apiVersion: v1
kind: Pod
metadata:
  name: Node-affinity
spec:
  containers:
    - name: nodeaffinity
      image: nginx:stable-alpine
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: NotIn
              values:
                - small
