apiVersion: v1
kind: Pod
metadata:
  name: node-server
spec:
  containers:
    - name: nodejs-web
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "nodejs"
      effect: "NoExecute"