apiVersion: v1
kind: Pod
metadata:
  name: mysql-database
  labels:
    database: mysql
spec:
  containers:
    - name: mysql-db
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mysql-config
