apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
spec:
  containers:
    - name: alpine-os
      image: alpine
      ports:
        - containerPort: 22
      resources:
       requests:
        memory: "64Mi"
        cpu: "200m"
       limits:
        memory: "128Mi"
        cpu: "300m"