apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
spec:
  containers:
    - name: alpine-os
      image: alpine
      ports:
        - containerPort: 22
      resources:
       requests:
        memory: "30Mi"
        cpu: "150m"
       limits:
        memory: "60Mi"
        cpu: "200m"