apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: myapp
    
spec:
  type: Nodeport
  selector:
    app: myapp
  ports:
    - targetPort: 80
      port: 80
      Nodeport: 3008