apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: nginx-web
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "web"
      effect: "NoSchedule"


