apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-test
spec:
  containers:
    - name: nfscont
      image: nginx

      volumeMounts:
        - name: nfs-test
          mountPath: "/var"
  volumes:
    - name: nfs-test
      persistentVolumeClaim:
        claimName: pvc-nfs


