apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-test
spec:
  containers:
    - name: nfscont
      image: nginx
      imagePullPolicy: Always
      volumeMounts:
        - name: nfs-test
          mountPath: "/usr/share/nginx/"
  volumes:
    - name: nfs-test
      persistentVolumeClaim:
        claimName: pvc-nfs


