apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostfile
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/test"



