apiVersion: v1
kind: Pod
metadata:
  name: pvpodhostfile
spec:
  containers:
    - name: testpvh
      image: ubuntu
      command:    # command arg is mandatory for ubuntu or os images
        - /bin/sleep
        - "300"
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: "/opt"
          name: test-pv-storage

  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: pvc-hostfile
p
