apiVersion: v1
kind: Pod
metadata:
  name: pv-test-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      volumeMounts:
        - mountPath: /opt
          name: pv-test-pod
  volumes:
    - name: pv-test-pod
      persistentVolumeClaim:
        claimName: pvc-mongodbdisk

