apiVersion: v1
kind: Pod
metadata:
  name: pvpodhostfile
spec:
  containers:
    - name: testpvh
      image: ubuntu
      imagePullPolicy: Always

      volumeMounts:
        - mountPath: "/opt"
          name: test-pv-storage

  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: pvc-hostfile

