apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: koganti
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dhMjluYm5ScE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXIxbEpnb2FCdEFMcmRiQjFKL2UxaEdtWW1NazNRVzVIVzV1eDRTSFFmNnV1Cng1ZmxicnVxV3ROdDNyZkg2SnNGRWNZV3JuamQ4dkJ4UjNHT0VNLzRWMmRQMWZaUW42aDVXQUNka3R2eTZjVFcKOFp1c3h2b0lwUitmMThoTlEvTmJhTVVEOUg5Y3NXeXorV25mb3pwcXlvektGbHhsd0UvVDN0N3Q0d2U5bVpsbgpvU3RNMHlDSitEcU93OUV5OTI3R3pOYlpJeFd5aUtnN0NsMDJXMjhjOTVOamh6Q3RKL0x5d0JNenRYcmZYWFlwCjV5em1qLzNraXJBN1dhV0RudkhpQTl2RlpWUEZFa2JMRnVURzZCdExubWRLYmJYc1FLRTF6aXU4emtlU1ZNam8KZG4wbFNSdDFTYTRpU1c2aEswdWJIL1c5TGNiSmJzZVRFUUxpQ29xUGl3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBS1dMaDJVY29iUG55a1lHWFJ6aTc2Sjd4NWZaRFdYS2h0c3hxNHRFdGt0Mm5kZXRDd0YwCnliT0cxZTdyRzVaNDJ2a3MxZXk2VkhlV1VoQ0lVMEkvdk1zVUR0NWNzOGFOVnhDUzdlMXErdUFVZlNzSlVvbG4KSGsyQXRld2l2a3NTckdHR1J4akt0Q3ovdEtEcUhKZjBobTYzaUZNdEF4Ny9GUXZ4Mm1ZcnNEUk5iaUtHbzU5WApkY0RRSEtuSzh5TUpjQlRsNmlUa0pLeTBzUHdWNktjZHNUSVVMQ3ZwbmVFQzVIVVV6a2pCMC9qYndZSlRlRjhtCkRaNFZBYXA0WlpaeW5xQTZvaTJVdTNRUTgyS1FCV1ZpeDByNWVnUXFOcVdUMUozZnVqU3FFbGt2TmVNQlBSVXEKejgwK2RCWEZpTXFMU2p1ZCtNNUFQejA1cUZENUo2SFFwWXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:

    - digital signature
    - key encipherment
    - server auth