apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admini_k8s
rules:
  - apiGroups: [""]
    resources:
      ["nodes", "namespace", "pods"]
    verbs:
      ["list", "create", "get", "delete"]
