apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: dev-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources:
      ["deployments", "replicaset", "pods"]
    verbs:
      ["get", "list", "watch", "create", "update", "delete"]


