apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rolebinding
  namespace: development
subjects:
  - kind: User
    name: developer
    apiGroup: ""

roleRef:
  kind: Role
  name: dev-role
  apiGroup: ""