apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-monitoring
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: m-agent
          image: nginx
          ports:
            - containerPort: 80

