apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
  - apiGroups: [""]
    resources:
      ["nodes", "namespace", "pods", "deployments", "service", "configmap"]
    verbs:
      ["get", "list", "watch", "create", "update", "patch", "delete"]

