apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rp
  labels:
    app: web
spec:
  template:
    metadata:
      name: httpd
      labels:
        app: web-server
        type: php
    spec:
      containers:
        - name: httpd-app
          image: httpd
  replicas: 2
  selector:
    matchLabels:
      type: php


