apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    app: http
    type: webserver
spec:
  template:
    metadata:
      name: web-doc
      labels:
        app: http
        type: webserver
    spec:


